[package]
name = "game-state"
version = "0.1.0"
authors = ["Luke Miles <luke.49@live.co.uk>"]
edition = "2018"

[dependencies]
lib = { path = "../lib" }
multiarray = "0.1"
higher_order_functions = "^0.1.1"
sized_matrix = "^0.2.2"
noise_fn = "^0.1.1"
