[package]
name = "game-client"
version = "0.1.0"
authors = ["Luke Miles <luke.49@live.co.uk>"]
edition = "2018"

[dependencies]
game-state = { path = "../game-state" }
game-interface = { path = "../game-interface" }
peer-client = { path = "../peer-client" }
